"""
kg_build.paths
----------------
Centralized path configuration for Phase 4: Knowledge Graph Build Pipeline.

This module exposes safe, absolute paths for:
- AlzForum processed CSVs
- Ontology processed files
- KG output directories (nodes, edges, Neo4j import)
- Utility helpers to ensure folders exist

All Phase 4 scripts should import paths from here instead of hardcoding paths.

Usage:
    from kg_build.paths import (
        ALZFORUM_PROCESSED_DIR,
        ONTOLOGY_PROCESSED_DIR,
        KG_OUTPUT_DIR,
        ensure_dirs
    )
"""

import os
from pathlib import Path


# -------------------------------------------------------------
# Project Root
# -------------------------------------------------------------
# This file lives in project_root/kg_build/
# So project_root = parent of kg_build
PROJECT_ROOT = Path(__file__).resolve().parent.parent


# -------------------------------------------------------------
# Source Directories (Phase 3 Outputs and Ontologies)
# -------------------------------------------------------------

# Alzforum processed CSV folder
ALZFORUM_PROCESSED_DIR = PROJECT_ROOT / "alzforum" / "processed"

# Ontology processed folder
ONTOLOGY_PROCESSED_DIR = PROJECT_ROOT / "ontology" / "processed"

# KG output directory
KG_OUTPUT_DIR = PROJECT_ROOT / "kg_build" / "output"

# Ontology raw folder (not always necessary in Phase 4)
ONTOLOGY_RAW = PROJECT_ROOT / "ontology" / "raw"


# -------------------------------------------------------------
# Phase 4 Output Folders (Canonical KG Nodes + Edges)
# -------------------------------------------------------------
KG_ROOT = PROJECT_ROOT / "kg_build"

# Where we store canonical node tables (Disease, Protein, Drug, etc.)
KG_NODES = KG_ROOT / "nodes"

# Where we store canonical edge tables (TREATS, TARGETS, BIOMARKER_OF, etc.)
KG_EDGES = KG_ROOT / "edges"

# Optional: Neo4j import directory (if using batch LOAD CSV)
NEO4J_IMPORT = PROJECT_ROOT / "neo4j_import"


# -------------------------------------------------------------
# Convenient access to specific Phase 3 CSV files
# -------------------------------------------------------------
# ALZPEDIA
ALZPEDIA_ENTITIES = ALZFORUM_PROCESSED_DIR / "alzpedia_entities.csv"
ALZPEDIA_SECTIONS = ALZFORUM_PROCESSED_DIR / "alzpedia_sections.csv"

# ALZBIOMARKERS
ALZBIOMARKER_BIOMARKERS = ALZFORUM_PROCESSED_DIR / "alzbiomarker_biomarkers.csv"
ALZBIOMARKER_EFFECTS = ALZFORUM_PROCESSED_DIR / "alzbiomarker_effects.csv"

# ALZRISK
ALZRISK_FACTORS = ALZFORUM_PROCESSED_DIR / "alzrisk_factors.csv"
ALZRISK_EFFECTS = ALZFORUM_PROCESSED_DIR / "alzrisk_effects.csv"

# THERAPEUTICS
THERAPEUTICS_ENTITIES = ALZFORUM_PROCESSED_DIR / "therapeutics_entities_enriched.csv"
THERAPEUTICS_TARGETS = ALZFORUM_PROCESSED_DIR / "therapeutics_targets.csv"
THERAPEUTICS_TRIALS = ALZFORUM_PROCESSED_DIR / "therapeutics_trials.csv"


# -------------------------------------------------------------
# Ontology Lookup Tables
# These will be generated by process_ontologies.py
# -------------------------------------------------------------
MONDO_INDEX = ONTOLOGY_PROCESSED_DIR / "mondo_index.json"
HGNC_INDEX = ONTOLOGY_PROCESSED_DIR / "hgnc_index.json"
UNIPROT_INDEX = ONTOLOGY_PROCESSED_DIR / "uniprot_index.json"
GO_INDEX = ONTOLOGY_PROCESSED_DIR / "go_index.json"
CHEBI_INDEX = ONTOLOGY_PROCESSED_DIR / "chebi_index.json"


# -------------------------------------------------------------
# Ensure All Directories Exist (idempotent)
# -------------------------------------------------------------
def ensure_dirs():
    """
    Create all important output directories if they do not exist.
    Safe to call multiple times.
    """
    for path in [
        KG_NODES,
        KG_EDGES,
        NEO4J_IMPORT,
        ONTOLOGY_PROCESSED_DIR,
    ]:
        path.mkdir(parents=True, exist_ok=True)


# Automatically create required dirs on import
ensure_dirs()


# -------------------------------------------------------------
# Debug: Print all paths (optional)
# -------------------------------------------------------------
if __name__ == "__main__":
    print("PROJECT_ROOT =", PROJECT_ROOT)
    print("ALZFORUM_PROCESSED_DIR =", ALZFORUM_PROCESSED_DIR)
    print("ONTOLOGY_PROCESSED_DIR =", ONTOLOGY_PROCESSED_DIR)
    print("KG_OUTPUT_DIR =", KG_OUTPUT_DIR)
    print("KG_NODES =", KG_NODES)
    print("KG_EDGES =", KG_EDGES)
    print("THERAPEUTICS_ENTITIES =", THERAPEUTICS_ENTITIES)